Software Recruitment Challenge
ParadigmHyperloop/recruiting-challenges pull request #1
Opened 2020-09-11 00:22 UTC by Burke-Daniel

## Overview
Initial pull request and implementation of software recruitment challenge. The idea is to have the recruits set up their development environment (text editor and git), clone the repo, make a branch, complete the coding part of the challenge, and submit a PR to this repo.

## Code
The code part of the code challenge consists of 3 classes, 1 of which the recruit is to complete.
 - The GPS class allows the user to obtain the boring machine's current position
 - The Steering class allows the user to interact with the "actuator" that controls the borer's pitch and yaw, as well as its forward movement.
 - The Navigation class will be implemented by the recruits.

@colton-smith feel free to change/add to this, I wrote all of this very fast and there may be mistakes or parts that could be a little more clear

2020-09-12 12:58 UTC, colton-smith requested changes
Looks mostly good, just have to move the docstrings to the correct location (you've been doing too much c++ hahahah) and possibly add some notes about classes - just remembered ENGI1020 doesnt cover OOP so we may have to just add a little blurb in the readme about classes (just attributes and methods basically). The other option is too just ask to them implement some functions that take a GPS object as a param, although its good for them to see classes as well! 

Since you're off in old trin town I'll fix this up !

2020-09-12 12:58 UTC, colton-smith commented on software-challenge/navigation.py
> +    """
These various docstrings should go underneath the function prototype :) I'll fix this up

2020-09-12 12:58 UTC, colton-smith commented on software-challenge/navigation.py
> +class will interface with our onboard GPS sensor to get thecurrent position, and
thecurrent -> the current

2020-09-12 12:58 UTC, colton-smith commented on software-challenge/navigation.py
> +    def set_desired_position(self, desired_position):
Should add a comment that indicates the user should implement the method.

2020-09-12 21:47 UTC, colton-smith commented
I updated all of the docstrings, and added to the readme, ready for re-review!

2020-09-13 21:38 UTC, Burke-Daniel reviewed
Aside from fixing my C++ docstrings, there are some nice documentation refinements here, good stuff.

2020-09-13 21:38 UTC, Burke-Daniel commented on fall-2020/README.md
> +* A class is like a blueprint for an object (oftem classes represent real world objects)
lil typo here

2020-09-13 21:38 UTC, Burke-Daniel commented on fall-2020/README.md
> +    def activate_vtec():
lol when the vtec kicks in 😲

2020-09-13 21:38 UTC, Burke-Daniel commented on fall-2020/README.md
> +To create an instance of the class, you simply call the constructor and provide the following arguements" make, model, max_speed, tire_size, is_coupe
lil typo here too

2020-09-13 21:38 UTC, Burke-Daniel commented on fall-2020/README.md
> +# GLHF !
We should see if the mechs can give the boring machine vtec

2020-09-14 22:06 UTC, Burke-Daniel commented
Just need an approval from you on this then will merge

2020-09-14 22:39 UTC, colton-smith approved these changes
GTM!

2020-09-14 22:40 UTC, merged